---
name: Geo-Google-PolylineEncoder
version: 0.02
author:
  - 'Steve Purkis <spurkis@cpan.org>'
abstract: encode lat/lngs to Google Maps Polylines
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Geo::Gpx: 0.01
  perl: 5.6.0
build_requires:
  IO::File: 0.01
  Module::Build: 0.20
  Test::More: 0.01
provides:
  Geo::Google::PolylineEncoder:
    file: lib/Geo/Google/PolylineEncoder.pm
    version: 0.02
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
